kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.SecretName}}
  namespace: {{.Release.Namespace}}
  labels:
    type: service-plan-claim
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
data:
  service-id: "98FF26D0-2E01-11E5-9184-FEFF819CDC9F"
  plan-id: "EAAD05D8-2E01-11E5-9184-FEFF819CDC9F"
  claim-id: "asdasd7234213"
  action: "create"
  target-name: "{{.Values.SecretName}}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  template:
    metadata:
        name: "{{.Release.Name}}"
        labels:
            heritage: {{.Release.Service | quote }}
            release: {{.Release.Name | quote }}
            chart: "{{.Chart.Name}}-{{.Chart.Version}}"
            component: "{{.Release.Name}}-{{.Values.Component}}"
        annotations:
            "helm.sh/created": {{.Release.Time.Seconds | quote }}
    spec:
      containers:
      - name: "{{.Release.Name}}"
        image: "{{.Values.Image}}:{{.Values.ImageTag}}"
        imagePullPolicy: "{{.Values.ImagePullPolicy}}"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "{{.Values.SecretName}}"
              key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{.Values.SecretName}}"
              key: password
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: "{{.Values.SecretName}}"
              key: name
      restartPolicy: Never