apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-steward"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-steward"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: {{.Values.ServicePort}}
    targetPort: {{.Values.ContainerPort}}
  selector:
    component: "{{.Release.Name}}-steward"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-steward"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-steward"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{default 1 .Values.Replicas | quote }}
  template:
    metadata:
      name: "{{ printf "%s-steward" .Release.Name | trunc 24 }}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-steward"
      annotations:
        "helm.sh/created": {{.Release.Time.Seconds | quote }}
    spec:
      containers:
      - name: "{{ printf "%s-steward" .Release.Name | trunc 24 }}"
        image: "{{.Values.StewardImage}}:{{.Values.StewardImageTag}}"
        imagePullPolicy: "{{.Values.StewardImagePullPolicy}}"
        env:
        - name: BROKER_NAME
          value: "{{ printf "%s-steward" .Release.Name | trunc 24 }}"
        - name: LOG_LEVEL
          value: trace
        - name: STEWARD_MODE
          value: cf
        - name: WATCH_NAMESPACES
          value: "{{.Values.StewardWatchNamespaces}}"
        - name: CF_BROKER_SCHEME
          value: "{{.Values.CfBrokerScheme}}"
        - name: CF_BROKER_HOSTNAME
          value: "{{.Release.Name}}-broker.{{.Release.Namespace}}.svc.cluster.local"
        - name: CF_BROKER_PORT
          value: "{{.Values.CfBrokerPort}}"
        - name: CF_BROKER_USERNAME
          value: "{{.Values.CfBrokerUsername}}"
        - name: CF_BROKER_PASSWORD
          value: "{{.Values.CfBrokerPassword}}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{.Values.ContainerPort}}
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{.Values.ContainerPort}}
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
